#!/usr/bin/env python3
"""Prepare public CodeParrot Python files for Code-JEPA.

This is the large-run pipeline for public, non-gated Python code. It stores whole-file
records, extracts function/method units, records AST spans, and materializes the current
conservative positive/hard-negative views for extracted units.

No tokenizer-specific artifacts are written.
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
import textwrap
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import pyarrow as pa
import pyarrow.parquet as pq
from datasets import load_dataset
from tqdm import tqdm

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from code_jepa.data.ids import stable_hash
from code_jepa.data.python_ast import ast_spans, line_count, loc_bucket, parse_and_compile, rough_token_len
from code_jepa.transforms.python_ast import hard_negative_views, positive_views


DATASET_NAME = "codeparrot/codeparrot-clean"
DATASET_CONFIG = "default"
SPLIT = "train"


def main() -> None:
    args = parse_args()
    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    stats: dict[str, Any] = {
        "started_at": now_iso(),
        "dataset": DATASET_NAME,
        "config": DATASET_CONFIG,
        "split": SPLIT,
        "args": vars(args) | {"output_dir": str(output_dir)},
        "counts": Counter(),
        "by_license": Counter(),
        "positive_transforms": Counter(),
        "negative_transforms": Counter(),
        "size_buckets": Counter(),
        "unit_types": Counter(),
    }

    process(args, output_dir, stats)
    stats["finished_at"] = now_iso()
    write_json(output_dir / "stats" / "transform-stats.json", normalize_stats(stats))
    write_json(output_dir / "manifests" / "dataset-manifest.json", manifest(args, output_dir, stats))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("/Volumes/SSD/datasets/code-jepa/processed/v0/codeparrot-python-1b"),
    )
    parser.add_argument("--target-raw-tokens", type=int, default=1_000_000_000)
    parser.add_argument("--max-files", type=int, default=None)
    parser.add_argument("--shard-size-files", type=int, default=5_000)
    parser.add_argument("--shard-size-units", type=int, default=25_000)
    parser.add_argument("--min-file-tokens", type=int, default=16)
    parser.add_argument("--max-file-chars", type=int, default=200_000)
    parser.add_argument("--min-loc", type=int, default=3)
    parser.add_argument("--max-loc", type=int, default=250)
    parser.add_argument("--max-units-per-file", type=int, default=64)
    parser.add_argument("--max-positive-views", type=int, default=3)
    parser.add_argument("--max-negative-views", type=int, default=5)
    parser.add_argument("--max-spans-per-unit", type=int, default=96)
    parser.add_argument("--compression", default="zstd")
    parser.add_argument("--store-file-source", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--skip-autogenerated", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--streaming", action=argparse.BooleanOptionalAction, default=True)
    return parser.parse_args()


def process(args: argparse.Namespace, output_dir: Path, stats: dict[str, Any]) -> None:
    dataset = load_dataset(DATASET_NAME, split=SPLIT, streaming=args.streaming)
    iterator: Iterable[dict[str, Any]] = dataset
    if args.max_files is not None:
        iterator = take(iterator, args.max_files)

    buffers: dict[str, list[dict[str, Any]]] = {
        "files": [],
        "units": [],
        "spans": [],
        "views": [],
        "triples": [],
        "relations": [],
    }
    shard_index = defaultdict(int)
    pbar = tqdm(iterator, total=args.max_files, desc="codeparrot", unit="file")

    for row_index, row in enumerate(pbar):
        stats["counts"]["input_files"] += 1
        if args.skip_autogenerated and str(row.get("autogenerated", "False")).lower() == "true":
            stats["counts"]["skipped_autogenerated"] += 1
            continue

        records = records_from_row(row, row_index, args, stats)
        if records is None:
            continue

        for table_name, recs in records.items():
            buffers[table_name].extend(recs)

        raw_tokens = records["files"][0]["rough_token_len"]
        stats["counts"]["raw_rough_tokens"] += raw_tokens
        pbar.set_postfix(
            raw_tokens=stats["counts"]["raw_rough_tokens"],
            kept_files=stats["counts"]["kept_files"],
            units=stats["counts"]["kept_units"],
        )

        flush_if_needed(output_dir, buffers, shard_index, args)

        if stats["counts"]["raw_rough_tokens"] >= args.target_raw_tokens:
            break

    flush_all(output_dir, buffers, shard_index, args.compression)


def records_from_row(
    row: dict[str, Any], row_index: int, args: argparse.Namespace, stats: dict[str, Any]
) -> dict[str, list[dict[str, Any]]] | None:
    source = row.get("content") or ""
    if not isinstance(source, str) or not source.strip():
        stats["counts"]["skipped_empty"] += 1
        return None
    if len(source) > args.max_file_chars:
        stats["counts"]["skipped_too_large"] += 1
        return None
    file_tokens = rough_token_len(source)
    if file_tokens < args.min_file_tokens:
        stats["counts"]["skipped_too_small"] += 1
        return None

    parsed = parse_and_compile(source)
    if parsed.tree is None or not parsed.parse_ok:
        stats["counts"]["skipped_parse"] += 1
        return None

    repo = str(row.get("repo_name") or "")
    path = str(row.get("path") or "")
    license_name = str(row.get("license") or "")
    file_hash = str(row.get("hash") or stable_hash([repo, path, source]))
    file_id = stable_hash([DATASET_NAME, repo, path, file_hash])
    stats["by_license"][license_name] += 1

    imports_context = imports_from_tree(parsed.tree, source)
    top_defs = top_defs_from_tree(parsed.tree)
    file_record = {
        "file_id": file_id,
        "dataset": DATASET_NAME,
        "dataset_config": DATASET_CONFIG,
        "split": SPLIT,
        "source_row_index": row_index,
        "repository_name": repo,
        "path": path,
        "language": "python",
        "license": license_name,
        "source_available": args.store_file_source,
        "source": source if args.store_file_source else "",
        "char_len": len(source),
        "loc": line_count(source),
        "rough_token_len": file_tokens,
        "parse_ok": parsed.parse_ok,
        "compile_ok": parsed.compile_ok,
        "top_defs_json": json.dumps(top_defs, ensure_ascii=False),
        "imports_context": imports_context,
        "metadata_json": json.dumps(
            {
                "copies": row.get("copies"),
                "size": row.get("size"),
                "hash": file_hash,
                "line_mean": row.get("line_mean"),
                "line_max": row.get("line_max"),
                "alpha_frac": row.get("alpha_frac"),
                "autogenerated": row.get("autogenerated"),
            },
            ensure_ascii=False,
            sort_keys=True,
        ),
    }

    unit_records: list[dict[str, Any]] = []
    span_records: list[dict[str, Any]] = []
    view_records: list[dict[str, Any]] = []
    triple_records: list[dict[str, Any]] = []
    relation_records: list[dict[str, Any]] = []

    for unit in extract_units(parsed.tree, source, max_units=args.max_units_per_file):
        code = unit["code"]
        loc = line_count(code)
        if loc < args.min_loc or loc > args.max_loc:
            stats["counts"]["skipped_unit_loc"] += 1
            continue
        unit_parse = parse_and_compile(code)
        if not unit_parse.parse_ok or not unit_parse.compile_ok:
            stats["counts"]["skipped_unit_parse_or_compile"] += 1
            continue

        unit_id = stable_hash([file_id, unit["qualified_name"], unit["start_line"], unit["end_line"], code])
        anchor_view_id = stable_hash([unit_id, "anchor", code])
        bucket = loc_bucket(loc)
        unit_record = {
            "unit_id": unit_id,
            "file_id": file_id,
            "dataset": DATASET_NAME,
            "dataset_config": DATASET_CONFIG,
            "split": SPLIT,
            "language": "python",
            "unit_type": unit["unit_type"],
            "qualified_name": unit["qualified_name"],
            "repository_name": repo,
            "path": path,
            "start_line": unit["start_line"],
            "end_line": unit["end_line"],
            "code": code,
            "imports_context": imports_context,
            "class_context": unit.get("class_context", ""),
            "loc": loc,
            "char_len": len(code),
            "rough_token_len": rough_token_len(code),
            "size_bucket": bucket,
            "parse_ok": unit_parse.parse_ok,
            "compile_ok": unit_parse.compile_ok,
            "error": unit_parse.error or "",
        }
        unit_records.append(unit_record)
        unit_spans = ast_spans(unit_id, code)[: args.max_spans_per_unit]
        span_records.extend(unit_spans)
        view_records.append(view_record(anchor_view_id, unit_id, "anchor", "anchor", code, "safe", [], {}))
        relation_records.append(
            {
                "relation_id": stable_hash([file_id, "contains", unit_id]),
                "file_id": file_id,
                "src_id": file_id,
                "dst_id": unit_id,
                "relation_type": "file_contains_unit",
                "metadata_json": "{}",
            }
        )

        pos_ids: list[tuple[str, str]] = []
        neg_ids: list[tuple[str, str, str]] = []
        for transform in positive_views(code, max_views=args.max_positive_views):
            view_id = stable_hash([unit_id, transform.role, transform.name, transform.code])
            view_records.append(
                view_record(
                    view_id,
                    unit_id,
                    transform.role,
                    transform.name,
                    transform.code,
                    transform.confidence,
                    transform.changed_spans,
                    transform.metadata,
                )
            )
            pos_ids.append((view_id, transform.name))
            stats["positive_transforms"][transform.name] += 1
        for transform in hard_negative_views(code, max_views=args.max_negative_views):
            view_id = stable_hash([unit_id, transform.role, transform.name, transform.code])
            neg_type = str(transform.metadata.get("negative_type", transform.name))
            view_records.append(
                view_record(
                    view_id,
                    unit_id,
                    transform.role,
                    transform.name,
                    transform.code,
                    transform.confidence,
                    transform.changed_spans,
                    transform.metadata,
                )
            )
            neg_ids.append((view_id, transform.name, neg_type))
            stats["negative_transforms"][transform.name] += 1
        for positive_view_id, positive_transform in pos_ids:
            for negative_view_id, negative_transform, negative_type in neg_ids:
                triple_records.append(
                    {
                        "triple_id": stable_hash([unit_id, positive_view_id, negative_view_id]),
                        "unit_id": unit_id,
                        "split": SPLIT,
                        "anchor_view_id": anchor_view_id,
                        "positive_view_id": positive_view_id,
                        "negative_view_id": negative_view_id,
                        "positive_transform": positive_transform,
                        "negative_transform": negative_transform,
                        "negative_type": negative_type,
                        "positive_strategy_label": "close",
                        "positive_semantic_label": "close",
                        "positive_local_label": "low_change",
                        "negative_strategy_label": "close",
                        "negative_semantic_label": "far",
                        "negative_local_label": "changed_span_important",
                    }
                )

        stats["counts"]["kept_units"] += 1
        stats["counts"]["views"] += 1 + len(pos_ids) + len(neg_ids)
        stats["counts"]["triples"] += len(pos_ids) * len(neg_ids)
        stats["counts"]["spans"] += len(unit_spans)
        stats["size_buckets"][bucket] += 1
        stats["unit_types"][unit["unit_type"]] += 1

    stats["counts"]["kept_files"] += 1
    return {
        "files": [file_record],
        "units": unit_records,
        "spans": span_records,
        "views": view_records,
        "triples": triple_records,
        "relations": relation_records,
    }


def extract_units(tree: ast.AST, source: str, *, max_units: int) -> list[dict[str, Any]]:
    units: list[dict[str, Any]] = []
    module_body = getattr(tree, "body", [])
    for node in module_body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            item = unit_from_node(node, source, unit_type="function", qualified_name=node.name)
            if item:
                units.append(item)
        elif isinstance(node, ast.ClassDef):
            class_context = class_signature(node)
            for child in node.body:
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    item = unit_from_node(
                        child,
                        source,
                        unit_type="method",
                        qualified_name=f"{node.name}.{child.name}",
                        class_context=class_context,
                    )
                    if item:
                        units.append(item)
        if len(units) >= max_units:
            break
    return units[:max_units]


def unit_from_node(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    source: str,
    *,
    unit_type: str,
    qualified_name: str,
    class_context: str = "",
) -> dict[str, Any] | None:
    segment = ast.get_source_segment(source, node)
    if not segment:
        return None
    return {
        "unit_type": unit_type,
        "qualified_name": qualified_name,
        "class_context": class_context,
        "start_line": int(getattr(node, "lineno", 0)),
        "end_line": int(getattr(node, "end_lineno", 0)),
        "code": textwrap.dedent(segment).rstrip() + "\n",
    }


def class_signature(node: ast.ClassDef) -> str:
    bases = [ast.unparse(base) for base in node.bases]
    suffix = f"({', '.join(bases)})" if bases else ""
    return f"class {node.name}{suffix}: ..."


def imports_from_tree(tree: ast.AST, source: str) -> str:
    lines = []
    for node in getattr(tree, "body", []):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            segment = ast.get_source_segment(source, node)
            if segment:
                lines.append(segment)
        elif not isinstance(node, ast.Expr):
            break
    return "\n".join(lines[:128])


def top_defs_from_tree(tree: ast.AST) -> list[dict[str, str]]:
    out = []
    for node in getattr(tree, "body", []):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            out.append({"name": node.name, "node_type": type(node).__name__})
    return out[:512]


def view_record(
    view_id: str,
    unit_id: str,
    role: str,
    transform_name: str,
    code: str,
    confidence: str,
    changed_spans: list[dict[str, Any]],
    metadata: dict[str, Any],
) -> dict[str, Any]:
    parsed = parse_and_compile(code)
    return {
        "view_id": view_id,
        "unit_id": unit_id,
        "split": SPLIT,
        "role": role,
        "transform_name": transform_name,
        "code": code,
        "parse_ok": parsed.parse_ok,
        "compile_ok": parsed.compile_ok,
        "confidence": confidence,
        "changed_spans_json": json.dumps(changed_spans, ensure_ascii=False),
        "metadata_json": json.dumps(metadata, ensure_ascii=False, sort_keys=True),
    }


def flush_if_needed(
    output_dir: Path,
    buffers: dict[str, list[dict[str, Any]]],
    shard_index: defaultdict[str, int],
    args: argparse.Namespace,
) -> None:
    if len(buffers["files"]) >= args.shard_size_files:
        flush_table(output_dir, "files", buffers, shard_index, args.compression)
    if len(buffers["units"]) >= args.shard_size_units:
        for table in ["units", "spans", "views", "triples", "relations"]:
            flush_table(output_dir, table, buffers, shard_index, args.compression)


def flush_all(
    output_dir: Path,
    buffers: dict[str, list[dict[str, Any]]],
    shard_index: defaultdict[str, int],
    compression: str,
) -> None:
    for table in list(buffers):
        flush_table(output_dir, table, buffers, shard_index, compression)


def flush_table(
    output_dir: Path,
    table_name: str,
    buffers: dict[str, list[dict[str, Any]]],
    shard_index: defaultdict[str, int],
    compression: str,
) -> None:
    records = buffers[table_name]
    if not records:
        return
    out_path = output_dir / table_name / f"shard-{shard_index[table_name]:05d}.parquet"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(pa.Table.from_pylist(records), out_path, compression=compression)
    buffers[table_name] = []
    shard_index[table_name] += 1


def take(items: Iterable[dict[str, Any]], n: int) -> Iterable[dict[str, Any]]:
    for index, item in enumerate(items):
        if index >= n:
            break
        yield item


def write_json(path: Path, obj: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, sort_keys=True) + "\n")


def normalize_stats(stats: dict[str, Any]) -> dict[str, Any]:
    out = dict(stats)
    for key in [
        "counts",
        "by_license",
        "positive_transforms",
        "negative_transforms",
        "size_buckets",
        "unit_types",
    ]:
        out[key] = dict(stats[key])
    return out


def manifest(args: argparse.Namespace, output_dir: Path, stats: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": "Code-JEPA CodeParrot Python v0 large run",
        "created_at": now_iso(),
        "output_dir": str(output_dir),
        "source_dataset": DATASET_NAME,
        "source_config": DATASET_CONFIG,
        "source_split": SPLIT,
        "tables": ["files", "units", "spans", "views", "triples", "relations"],
        "target_raw_tokens": args.target_raw_tokens,
        "raw_rough_tokens": int(stats["counts"].get("raw_rough_tokens", 0)),
        "tokenized": False,
        "notes": [
            "Whole-file source records with extracted function/method train units.",
            "Hard negatives are behavior-impacting mutations relative to the original, not proven failing programs.",
            "No tokenizer-specific fields are written.",
        ],
        "counts": dict(stats["counts"]),
    }


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


if __name__ == "__main__":
    main()
